apiVersion: v1
kind: Service
metadata:
  labels:
    run: farkhodsadykov
  name: farkhodsadykov
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    run: farkhodsadykov
  type: LoadBalancer
